# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Declare the Python requirements required to build docs
python:
  install:
    - requirements: requirements.txt
    # st2/ is st2.git cloned in post_checkout job
    - requirements: st2/requirements.txt

# Set the version of Python and other tools, and customize the build process
build:
  os: ubuntu-20.04
  tools:
    # python: "3.6"
    python: "3.8"
  apt_packages:
    - python3-dev
    - libldap2-dev
    - libsasl2-dev

  # https://docs.readthedocs.io/en/stable/build-customization.html#extend-the-build-process
  # NOTE: use " instead of ' for all quoting or RTD gives some weird errors.
  jobs:
    post_checkout:
      - ./scripts/clone-st2.sh
      - ./scripts/clone-orquesta.sh

    # We can't control the version of pip installed because it is part of the `install` stage.
    #pre_install:
    #  # switch to version of pip from cloned copy of st2
    #  - >
    #    export PIP_VERSION=$(grep "PIP_VERSION ?= " st2/Makefile | awk "{ print \$3 }");
    #    echo PIP_VERSION=${PIP_VERSION};
    #    pip install --upgrade "pip==${PIP_VERSION}";

    # install: see python.install above

    post_install:
      - cd ./st2; make virtualenv
      - cd ./st2; make requirements
      # generate-runner-parameters-documentation.py needs this in the st2 virtualenv
      - . st2/virtualenv/bin/activate; pip install pytablewriter

    pre_build:
      - . st2/virtualenv/bin/activate; ./scripts/generate-runner-parameters-documentation.py
      - . st2/virtualenv/bin/activate; ./scripts/generate-internal-triggers-table.py
      - . st2/virtualenv/bin/activate; ./scripts/generate-available-permission-types-table.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

