name: Publish Docs

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - ".github/workflows/publish-docs.yml"
      - "Makefile"


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        python_version: python3.8
      run: |
        make st2
        sudo apt-get update
        # python3-dev is already available
        # sudo apt install python3-dev
        sudo apt install libldap2-dev 
        sudo apt install libsasl2-dev
        sudo pip3 install virtualenv
        make docs

        # turn off jekyll so that url routing works properly with underscores
        touch docs/build/html/.nojekyll
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html